<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body style = "color:green;background-color:red;text-shadow: 1px 1px 2px yellow;font-family: 'Comic Sans MS', cursive, sans-serif;">
	<h1 >PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
	<h1>PARABÉNS VOCÊ DESVENDOU UM MISTÉRIO</h1>
</body>
</html>